### PR TITLE
add OpenAI Classifier

### PR DESCRIPTION
**Pull request by Rajaniraiyn**
**Issue number:** #85

### Changes

Added an OpenAI classifier as an inbuilt feature. Updated the relevant documentation to reflect the new functionality. This change eliminates the need for users to create custom classifiers by enabling seamless integration of OpenAI's classifier.

### User experience

**Before:** Users were required to write custom classifiers to integrate OpenAI's functionality, adding additional development effort and complexity.  
**After:** The OpenAI classifier is now available as a built-in feature, improving DX.

## Checklist

* [x] I have performed a self-review of this change  
* [x] Changes have been tested  
* [x] Changes are documented  

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by brnaba-aws** [comment]
Hi @Rajaniraiyn 
Thanks a lot for your contribution 🙌 

We will review the code, test it and come back with feedback, if any.

**Comment by brnaba-aws** [comment]
@leonardo2204 , feel free to contribute and add function call for OpenAi agent (both TS and python :) )

**Comment by leonardo2204** [comment]
@brnaba-aws https://github.com/awslabs/multi-agent-orchestrator/pull/96

**Comment by Rajaniraiyn** [comment]
Hi @brnaba-aws

Thank you for your response earlier. I just wanted to follow up and check if there’s any update regarding the review. Please let me know if you need any additional information or clarification from my side to assist with the process.

**Comment by brnaba-aws** [comment]
@Rajaniraiyn Thanks a lot for your work. 
I'll merge the pull request now. 
Please don't hesitate to share the contribution on you have made to the framework on social media. 

It is making it even better 🚀 ❤️

**Comment by brnaba-aws** [comment]
@Rajaniraiyn Do you think you can contribute to the same classifier for python? :)

**Comment by Rajaniraiyn** [comment]
@brnaba-aws https://github.com/awslabs/multi-agent-orchestrator/pull/101

**Pull request merged**
