### PR TITLE
Add SQL Conversation Storage

### PR DESCRIPTION
**Pull request by Rajaniraiyn**
**Issue number:** #110

### Changes

This PR adds a new feature, **SQL Storage**, to the Multi-Agent Orchestrator system. It introduces persistent conversation storage using the [`libsql`](https://github.com/tursodatabase/libsql) library, supporting both local SQLite databases and remote databases. This implementation improves flexibility, reliability, and scalability for storing agent conversation history.

### User experience

**Before this change**:
- Conversation data was limited to DynamoDB or in-memory storage without a CustomStorage implementation.

**After this change**:
- Users can store conversations persistently with support for both local and remote databases.
- Provides robust solutions for edge and serverless deployments.
- Simplifies setup with automatic schema creation and indexing.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented

<details>
<summary>Is this a breaking change? No</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by fryz** [comment]
Any update on this PR? 

I've got a similar use-case where we're using a SQL DB for storing conversations. 
I've rolled my own storage engine for this outside of the multi-agent orchestrator framework, but having this built-in would be pretty nice. 

Looks like the current HEAD of this fork needs a rebase. Happy to contribute if OP no longer has the bandwidth, but also not sure if the maintainers are willing to accept this. Looking for some feedback either way. 

Thanks!

**Comment by Rajaniraiyn** [comment]
Hey @cornelcroi
I have made the requested changes,
- made `libsql` installing when only used in python
- mention sql storage in overview docs

Thanks

**Comment by cornelcroi** [comment]
Can you add the pip install with the package like we did [here](http://localhost:4321/multi-agent-orchestrator/agents/built-in/bedrock-llm-agent) ?
The users are more likely to skip the initial installation step so if they head to this storage, the installation of the lib must be recalled.

Thanks.

**Comment by Rajaniraiyn** [comment]
@cornelcroi I have updated both DynamoDB and SQL storage docs for python, specifying extras dependency installation. Let me know any further changes required.
Thanks.

**Comment by cornelcroi** [comment]
Great, thanks.
Merging.

**Comment by fryz** [comment]
Thanks for merging this :)

**Comment by psqbt** [comment]
I am getting this error while using the SqlChatStorage with local db file

image

I am setting up the orchestrator in the fast api async method same as in [fastapi streaming example](https://github.com/awslabs/multi-agent-orchestrator/tree/main/examples/fast-api-streaming)

image

image

**Comment by cornelcroi** [comment]
@fryz can you have a look?

**Comment by cornelcroi** [comment]
> CC @Rajaniraiyn (original contributor) 
> 
> 
> 
> Would be happy to contribute but I'm more familiar with the Typescript side of things. 
> 
> Looks like it's because the query invoking the read from the DB is async and not being handled correctly? (eg: `await`?) 
> 
> 

Sorry, I meant to tag the original author 😊

**Comment by psqbt** [comment]
> CC @Rajaniraiyn (original contributor)
> 
> Would be happy to contribute but I'm more familiar with the Typescript side of things. Looks like it's because the query invoking the read from the DB is async and not being handled correctly? (eg: `await`?)

@fryz Yes, async method not awaited....full trace below

image

**Comment by psqbt** [comment]
Thanks @Rajaniraiyn !

**Pull request merged**
